# Generated by Django 4.2 on 2023-12-20 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=9.0),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='mc_donalds.ProductOrder', to='mc_donalds.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mc_donalds.staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='time_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(default='Состав не указан'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mc_donalds.order'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mc_donalds.product'),
        ),
    ]
