# Generated by Django 4.2 on 2023-12-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0003_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='classifier',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
