# Generated by Django 4.2 on 2023-12-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0004_country_classifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='classifier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
