# Generated by Django 4.2 on 2023-12-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0005_alter_country_classifier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
