# Generated by Django 4.2 on 2023-12-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0006_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('classifier', models.CharField(blank=True, max_length=10)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
